-- Şehirlere göre verilen siparişleri toplam olarak listeleme
SELECT 
CT.CITY SEHIR, SUM(O.TOTALPRICE) CIRO,
COUNT(O.ID) SIPARISSAYISI
FROM ORDERS O
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN CITIES CT ON CT.ID=A.CITYID
GROUP BY CT.CITY

-- SİPARİŞLERİN ORTALAMA KARGOLAMA SÜRELERİNİ GETİRME

SELECT CT.CITY SEHIR,T.TOWN ILCE, AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) HAZIRLIKSURESI
FROM ORDERS O
JOIN INVOICES I ON I.ORDERID = O.ID
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN CITIES CT ON CT.ID = A.CITYID
JOIN TOWNS T ON T.ID = A.TOWNID
WHERE CT.CITY = 'İSTANBUL'
GROUP BY CT.CITY, T.TOWN


--YAŞ GRUPLARINA GÖRE SİPARİŞ DAĞILIMI
SELECT 
YASARALIGI, SUM(SIPARISTOPLAMI) SIPARISTOPLAMI
FROM
(
SELECT 
DATEDIFF(YEAR, U.BIRTHDATE,GETDATE()) YAS,
CASE 
	WHEN DATEDIFF(YEAR, U.BIRTHDATE,GETDATE()) BETWEEN 20 AND 30 THEN '20-30 YAŞ ARASI'
	WHEN DATEDIFF(YEAR, U.BIRTHDATE,GETDATE()) BETWEEN 31 AND 40 THEN '31-40 YAŞ ARASI'
	WHEN DATEDIFF(YEAR, U.BIRTHDATE,GETDATE()) BETWEEN 41 AND 50 THEN '41-50 YAŞ ARASI'
	WHEN DATEDIFF(YEAR, U.BIRTHDATE,GETDATE()) BETWEEN 51 AND 60 THEN '51-60 YAŞ ARASI'
	WHEN DATEDIFF(YEAR, U.BIRTHDATE,GETDATE()) BETWEEN 61 AND 70 THEN '61-70 YAŞ ARASI'
	WHEN DATEDIFF(YEAR, U.BIRTHDATE,GETDATE()) BETWEEN 71 AND 80 THEN '71-80 YAŞ ARASI'
	WHEN DATEDIFF(YEAR, U.BIRTHDATE,GETDATE()) >80 THEN '80-90 YAŞ ARASI'
END AS YASARALIGI,

SUM(O.TOTALPRICE) SIPARISTOPLAMI
FROM USERS U
JOIN ORDERS O ON O.USERID = U.ID
GROUP BY DATEDIFF(YEAR, U.BIRTHDATE,GETDATE())
) T
GROUP BY YASARALIGI
ORDER BY YASARALIGI



--ÜRÜN ANALİZİ
-- ilk ne zaman satıldı?
-- son ne zaman satıldı?
-- en ucuz hangi fiyattan satıldı?
-- en yüksek hangi fiyattan satıldı?
-- ortalama hangi fiyattan satıldı?
-- toplam ne kadar ciro yaptı?
-- toplam kaç adet satıldı?

SELECT
I.ITEMCODE URUNKODU, I.ITEMNAME URUNADI, I.BRAND MARKA , I.CATEGORY1 KATEGORI1, I.CATEGORY2 KATEGORI2,
MIN(O.DATE_) ILKSATISTARIHI, MAX(O.DATE_) SONSATISTARIHIİ,
MIN(OD.UNITPRICE) ENDUSUKFIYAT, MAX(OD.UNITPRICE) ENYUKSEKFIYAT,
AVG(OD.UNITPRICE) ORTALAMAFIYAT, SUM(OD.LINETOTAL) CIRO, SUM(OD.LINETOTAL) MIKTAR
FROM ITEMS I
JOIN ORDERDETAILS OD ON OD.ITEMID = I.ID
JOIN ORDERS O ON O.ID = OD.ORDERID

GROUP BY I.ITEMCODE, I.ITEMNAME, I.BRAND, I.CATEGORY1, I.CATEGORY2

-- BİR MÜŞTERİNİN BENDEN NE KADAR ALIŞVERİŞ YAPTIĞI BİLGİSİNİ GETİRMEK

SELECT 
U.ID, U.NAMESURNAME, SUM(O.TOTALPRICE), COUNT(O.USERID)
FROM USERS U
JOIN ORDERS O ON O.USERID = U.ID

GROUP BY U.ID, U.NAMESURNAME


--SUBQUARY YÖNTEMİ

SELECT U.ID, U.NAMESURNAME,
(SELECT SUM(TOTALPRICE) FROM ORDERS WHERE USERID=U.ID) SIPARISTOPLAMI,
(SELECT COUNT(*) FROM ORDERS WHERE USERID=U.ID) SIPARISSAYISI
FROM USERS U


--BİR KULLANICININ EN SON ALIŞVERİŞ YAPTIĞI ADRESİ GETİRME

SELECT U.ID, U.USERNAME_,
	(SELECT TOP 1 A.ADDRESSTEXT FROM ORDERS O
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE O.USERID = U.ID
	ORDER BY O.DATE_ DESC
	)
SONADRES FROM USERS U




