select U.USERNAME_, U.NAMESURNAME, U.EMAIL, U.BIRTHDATE,
C.COUNTRY, CT.CITY, T.TOWN, D.DISTRICT,
A.POSTALCODE, A.ADDRESSTEXT

from USERS U, ADDRESS A,
COUNTRIES C, CITIES CT,
TOWNS T, DISTRICTS D

WHERE U.ID = A.USERID 
AND C.ID =A.COUNTRYID
AND CT.ID = A.CITYID
AND T.ID=A.TOWNID
AND D.ID = A.DISTRICTID

SELECT U.USERNAME_, U.NAMESURNAME, U.EMAIL, U.BIRTHDATE,
C.COUNTRY , CT.CITY, T.TOWN, D.DISTRICT, A.POSTALCODE, A.ADDRESSTEXT
FROM USERS U
JOIN ADDRESS A ON U.ID=A.USERID
JOIN COUNTRIES C ON C.ID = A.COUNTRYID
JOIN CITIES CT ON CT.ID = A.CITYID
JOIN TOWNS T ON T.ID = A.TOWNID
JOIN DISTRICTS D ON D.ID = A.DISTRICTID