SELECT COUNT(*) SATIRSAYISI, SUM(TOTALPRICE) CIRO,
SUM(AMOUNT) TOPLAMADET, MIN(PRICE) ENDUSUKFIYAT, 
MAX(PRICE) ENYUKSEKFIYAT, AVG(PRICE) ORTALAMAFIYAT
FROM SALES

--WHERE KULLANIMI

SELECT COUNT(*) SATIRSAYISI, SUM(TOTALPRICE) CIRO,
SUM(AMOUNT) TOPLAMADET, MIN(PRICE) ENDUSUKFIYAT, 
MAX(PRICE) ENYUKSEKFIYAT, AVG(PRICE) ORTALAMAFIYAT
FROM SALES WHERE CITY = 'İSTANBUL'

SELECT SUM(TOTALPRICE) FROM SALES WHERE CITY = 'ANKARA'

SELECT SUM(TOTALPRICE) FROM SALES WHERE CITY = 'İSTANBUL'

SELECT CITY SEHIR, SUM(TOTALPRICE) CIRO FROM SALES 
GROUP BY CITY 
ORDER BY SUM(TOTALPRICE) DESC

SELECT REGION BOLGE, CITY SEHIR, SUM(TOTALPRICE) CIRO 
FROM SALES 
GROUP BY REGION ,CITY
ORDER BY REGION

-- BİR MAĞAZANIN GÜN BAZLI SATIŞ RAKAMINI GETİRME

SELECT CONVERT(DATE,DATE_) TARIH, SUM(TOTALPRICE) CIRO FROM SALES 
WHERE CITY='İSTANBUL'
GROUP BY CONVERT(DATE,DATE_)
ORDER BY CONVERT(DATE,DATE_)

-- BİR GÜNÜN MAĞAZA BAZLI SATIŞLARINI GETİRME

SELECT CITY SEHİR, SUM(TOTALPRICE) CIRO 
FROM SALES WHERE DATE_ BETWEEN '2019-08-02 00:00:00' AND '2019-08-02 23:59:59' -- CONVERT(DATE, DATE_) = '2019-08-02' DİYEREK GETİREBİLİRDİK

GROUP BY CITY 
ORDER BY 2 DESC -- ORDER BY CIRO DESC

-BELLİ BİR CİRONUN ÜSTÜNDE SATIŞL YAPAN MAĞAZALARI GETİRME

SELECT CITY SEHİR, SUM(TOTALPRICE) CIRO
FROM SALES 
GROUP BY CITY
HAVING SUM(TOTALPRICE)>100000 -- WHERE KULLANILMAZ GROUPBYDAN SONRA HAVING KULLANILIR
ORDER BY CIRO DESC

-- MAĞAZALARIN AYLARA GÖRE SATIŞLARINI GETİRME
SET LANGUAGE Turkish
SELECT CITY SEHIR, DATENAME(MONTH,DATE_) AY,
SUM(TOTALPRICE) CIRO
FROM SALES
GROUP BY CITY, DATENAME(MONTH,DATE_), DATEPART(MONTH,DATE_)
ORDER BY CITY, DATEPART(MONTH,DATE_)


-- ÜRÜN KATEGORİLERİNE GÖRE SATIŞLARI GETİRME

SELECT CATEGORY1 KATEGORI,
CATEGORY2 KATEGORI2,
SUM(TOTALPRICE) CIRO FROM SALES
GROUP BY CATEGORY1, CATEGORY2 
ORDER BY CATEGORY1, SUM(TOTALPRICE) DESC


--MAĞAZALARIN MÜŞTERİ SAYILARINI GETİRME
SELECT * FROM SALES

SELECT CITY SEHIR, 
COUNT(DISTINCT CUSTOMERCODE) MUSTERISAYISI
FROM SALES
GROUP BY CITY
ORDER BY CITY

--MAĞAZALARIN FATURA SAYILARINI GETİRME

SELECT CITY SEHIR, 
COUNT(DISTINCT FICHENO) FATURASAYISI
FROM SALES
GROUP BY CITY
ORDER BY CITY




