SELECT 
[ID], [TCNUMBER], [NAMESURNAME], [GENDER], [EMAIL], 
[BIRTHDATE], [CITY], [DISTRICT], [TELNR1], [TELNR2], [FATHER NAME]
FROM CUSTORMERS

SELECT * FROM CUSTORMERS

INSERT INTO CUSTORMERS
(TCNUMBER,NAMESURNAME,GENDER,EMAIL,BIRTHDATE,CITY,DISTRICT,TELNR1,TELNR2)
VALUES
(44444444444,'NEHİR IŞIK','K','nisik@xyz.com','01.01.1990','Ankara','Keçiören','(554)1234567','(553)1234567')



INSERT INTO CUSTORMERS(TCNUMBER,NAMESURNAME,GENDER,EMAIL,BIRTHDATE,CITY,DISTRICT,TELNR1,TELNR2) 
VALUES ('42074151323',

SELECT *FROM CUSTOMERS

DELETE FROM CUSTOMERS --TABLOYU SİLER ID SIFIRLAMAZ - WHERE KULLANILIR YANİ FİLTRELİ SİLEBİLİR

TRUNCATE TABLE CUSTOMERS -- SİLER VE ID SIFIRLAR 

INSERT INTO CUSTORMERS(TCNUMBER,NAMESURNAME,GENDER,EMAIL,BIRTHDATE,CITY,DISTRICT,TELNR1,TELNR2) 
VALUES ('42074151323','Sevda AKÇAN','K','s_akcan@miuul.com','1964-05-12','EDİRNE','EMET','(542)5255514','(532)3438190')


UPDATE CUSTORMERS 
SET AGE=DATEDIFF(YEAR,BIRTHDATE,'2023-07-24')

SELECT * FROM CUSTOMERS WHERE ID=2


SELECT * FROM CUSTOMERS WHERE CITY = 'İSTANBUL'

SELECT * FROM CUSTOMERS WHERE CITY <> 'İSTANBUL' -- istanbul harici getir

SELECT * FROM CUSTOMERS WHERE not CITY = 'İSTANBUL' -- istanbul harici getir

SELECT * FROM CUSTOMERS WHERE ID>500

SELECT * FROM CUSTOMERS WHERE BIRTHDATE<'1980-01-01'

SELECT * FROM CUSTOMERS WHERE ID BETWEEN 2 AND 10

SELECT * FROM CUSTOMERS WHERE NAMESURNAME BETWEEN 'A' AND 'C'

SELECT * FROM CUSTOMERS WHERE CITY IN ('İSTANBUL','ANKARA','İZMİR')

SELECT * FROM CUSTOMERS WHERE NAMESURNAME LIKE 'ALİ%' -- İSMİ ALİYLE BAŞLAYANLAR 

SELECT * FROM CUSTOMERS WHERE NAMESURNAME LIKE '%ALİ%' -- İSMİNDE ALİ GEÇENLER

SELECT * FROM CUSTOMERS WHERE NAMESURNAME LIKE '%UÇAR' -- SOYİSMİNDE UÇAR GEÇENLER

SELECT * FROM CUSTOMERS WHERE NAMESURNAME LIKE '% ALİ %' -- BOŞLUK OLDUĞU İÇİN 2. ADINDA ALİ GEÇENLERİ GETİRİYOR

SELECT * FROM CUSTOMERS WHERE CITY = 'İSTANBUL'  --CITY = İSTANBUL 47 

SELECT * FROM CUSTOMERS WHERE GENDER = 'E' -- GENDER  = E 451

SELECT * FROM CUSTOMERS WHERE CITY = 'İSTANBUL' AND GENDER = 'E' --21

SELECT * FROM CUSTOMERS WHERE CITY = 'İSTANBUL' AND GENDER = 'K' --26

SELECT * FROM CUSTOMERS WHERE CITY = 'İSTANBUL' AND DISTRICT = 'AVCILAR' AND DISTRICT = 'ADALAR' -- BOŞ GELİR

SELECT * FROM CUSTOMERS WHERE BIRTHDATE BETWEEN	'1980-01-01' AND '1990-12-31' 

SELECT * FROM CUSTOMERS WHERE BIRTHDATE>='1980-01-01' AND BIRTHDATE<='1990-12-31' -- YUKARIDAKİ DEĞERLE AYNI İŞLEM

--OR OPERATÖRÜ

SELECT * FROM CUSTOMERS WHERE CITY = 'İZMİR' OR CITY = 'İSTANBUL' OR CITY= 'ANKARA' -- ÜÇÜNÜN TOPLAMINI GETİRDİ

SELECT * FROM CUSTOMERS WHERE CITY IN ('İZMİR', 'İSTANBUL', 'ANKARA') -- AYNI SONUCU GETİRDİ

SELECT * FROM CUSTOMERS WHERE CITY = 'İSTANBUL' OR GENDER = 'E'

-- CITY = İSTANBUL 47
-- GENDER = E 47

SELECT * FROM CUSTOMERS WHERE CITY = 'İSTANBUL' AND DISTRICT = 'AVCILAR' OR GENDER = 'E'
-- PARANTEZ KULLANMAZSAK OR TÜM SATIRLARI EZER YANİ ERKEKLERİN HEPSİNİ GETİRİR

SELECT * FROM CUSTOMERS WHERE CITY = 'İSTANBUL' AND (DISTRICT = 'AVCILAR' OR GENDER = 'E') --23


--CITY = 47
--DISTRICT = 4
--GENDER= 451

SELECT * FROM CUSTOMERS 

UPDATE CUSTOMERS SET COUNTRY = 'TÜRKİYE'

UPDATE CUSTOMERS SET AGE = DATEDIFF(YEAR, BIRTHDATE , '2023-07-26')

UPDATE CUSTOMERS SET AGEGROUP = '20-30 YAŞ ARASI' WHERE AGE BETWEEN 20 AND 30

UPDATE CUSTOMERS SET AGEGROUP = '31-40 YAŞ ARASI' WHERE AGE BETWEEN 31 AND 40

UPDATE CUSTOMERS SET AGEGROUP = '41-50 YAŞ ARASI' WHERE AGE BETWEEN 41 AND 50

UPDATE CUSTOMERS SET AGEGROUP = '51-60 YAŞ ARASI' WHERE AGE BETWEEN 51 AND 60

UPDATE CUSTOMERS SET AGEGROUP = '61-70 YAŞ ARASI' WHERE AGE BETWEEN 61 AND 70

UPDATE CUSTOMERS SET AGEGROUP = '71-30 YAŞ ARASI' WHERE AGE BETWEEN 71 AND 80

UPDATE CUSTOMERS SET AGEGROUP = '81-90 YAŞ ARASI' WHERE AGE BETWEEN 81 AND 90

UPDATE CUSTOMERS SET TELOPERATOR1 = 'T OPERATORÜ' WHERE TELNR1 LIKE '(54%'

UPDATE CUSTOMERS SET TELOPERATOR2 = 'X OPERATORÜ' WHERE TELNR2 LIKE '(55%'


UPDATE CUSTOMERS SET GENDER = 'ERKEK' WHERE GENDER = 'E'

UPDATE CUSTOMERS SET GENDER = 'KADIN' WHERE GENDER = 'K'

--DISTINCT KOMUTU

SELECT DISTINCT CITY,DISTRICT FROM CUSTOMERS WHERE CITY = 'İSTANBUL' -- TEKRAR ETMEYEN VERİLERİ GETİRİR

SELECT DISTINCT AGEGROUP FROM CUSTOMERS

-- ORDER BY KOMUTU

SELECT * FROM CUSTOMERS ORDER BY NAMESURNAME ASC --a DAN Z YE

SELECT * FROM CUSTOMERS ORDER BY NAMESURNAME DESC -- Z DEN A YA

SELECT * FROM CUSTOMERS ORDER BY BIRTHDATE

SELECT * FROM CUSTOMERS ORDER BY CITY,DISTRICT

SELECT * FROM CUSTOMERS ORDER BY CITY,BIRTHDATE DESC

SELECT * FROM CUSTOMERS WHERE CITY = 'İSTANBUL' ORDER BY CITY,DISTRICT,GENDER -- SADECE İSTANBUL ŞEHRİ SIRLAMADA İLÇE ALFABETİK VE CİNSİYET ALFABETİK

-- TOP KOMUTU

SELECT TOP 10 * FROM CUSTOMERS WHERE CITY = 'İSTANBUL' ORDER BY BIRTHDATE DESC -- İSTANBULDAKİ EN GENÇ 10 MÜŞTERİ

SELECT TOP 10 * FROM CUSTOMERS WHERE CITY = 'İSTANBUL' AND GENDER = 'ERKEK' ORDER BY BIRTHDATE DESC -- İSTANBULDAKİ EN GENÇ 10 ERKEK

SELECT TOP 10 PERCENT * FROM CUSTOMERS WHERE GENDER = 'ERKEK' ORDER BY BIRTHDATE DESC -- TOPLAM YÜZDESEL OLARAK YÜZDE 10 

-- DDL KOMUTLARI (CREATE, ALTER, DROP)

CREATE TABLE CUSTOMERS2
(
ID INT,TCNUMBER VARCHAR(13), NAMESURNAME VARCHAR(100), GENDER VARCHAR(1), 
EMAIL VARCHAR(100), BIRTHDATE DATE, CITY VARCHAR(50), DISTRICT VARCHAR (50), 
TELNR1 VARCHAR(15), TELNR2 VARCHAR(15)
)
-- TABLOYA YENİ BİR ALAN EKLEMEK İÇİN
ALTER TABLE CUSTOMERS2 
ADD COUNTRY VARCHAR(50)

ALTER TABLE CUSTOMERS2
ADD COUNTRY VARCHAR(50), AGE INT, AGEGROUP VARCHAR(50), TELOPERATOR1 VARCHAR(50), TELOPERATOR2 VARCHAR(50)

--TABLODAN BİR ALANI SİLMEK İÇİN
ALTER TABLE CUSTOMERS2
DROP COLUMN AGE, AGEGROUP,TELOPERATOR1,TELOPERATOR2

--TABLODAKİ BİR ALANI DEĞİŞTİRMEK İÇİN
ALTER TABLE CUSTOMERS2
ALTER COLUMN GENDER VARCHAR(10)

-- TABLOYA OTOMATİK ARTAN ALAN EKLEMEK İÇİN
ALTER TABLE CUSTOMERS2
DROP COLUMN ID

ALTER TABLE CUSTOMERS2
ADD ID INT IDENTITY(1,1)

--TABLOYA PRIMARY KEY EKLEMEK İÇİN

ALTER TABLE CUSTOMERS2
ADD CONSTRAINT PK_CUSTOMERS2 PRIMARY KEY (ID)

-- TABLODAN PRIMARY KEY SİLMEK İÇİN

ALTER TABLE CUSTOMERS2
DROP CONSTRAINT PK_CUSTOMERS2

